# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets: ['localhost:9096']

rule_files:
  - "/etc/prometheus/alerting_rules.yml"

scrape_configs:
  - job_name: 'kafka-consumer'
    static_configs:
      - targets: ['localhost:9200']
